### ISSUE TITLE
Worked very well (not really an issue just wanted to say thanks for the code)

### ISSUE THREAD

**Issue by cygnus-glacier** [LionyxML/migrate-github-to-codeberg#1]
This script worked really well. In terms of permissions I needed to set in the GitHub API for private repositories I did toggle the following ones:
### Repository Permissions:

- Actions: Read and Write, 
- Administration: Read and Write
- Contents: Read and Write

Then there was Metadata (mandatory): Read Only

I was not sure how many of these was necessary to turn on (if any) but it worked. Thank you!

**Comment by LionyxML** [comment]
My pleasure!

Indeed this script is meant to be tweakable, as I also can't keep up with both github and codeberg api changes :)
